# Generated by Django 2.2.6 on 2019-10-03 19:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.parent_image_file_path),
        ),
    ]
